name: Lint & Test
on:
  push:
    branches:
      - '*'
      - '!delivery'
      - '!next'
  workflow_call:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init & Build
        uses: ./.github/actions/build

      - name: Run lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:jest
